<a href="https://colab.research.google.com/github/GusdPaula/ML_interview/blob/main/attention_mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Attention mechanism

In [1]:
import numpy as np

# Step 1: Define Query(Q), Key (K), and Value (V) matrices
Q = np.array([[1, 0, 1]]) # Query vector (1x3)
K = np.array([[1, 1, 0], [1, 1, 0], [0, 0, 1]]) # Key vectors (3x3)
V = np.array([[1, 2],
              [0, 3],
              [1, 1]]) # Value vectors (3x2)

# Step 2: Compute dot product between Q and K^T (similarity scores)
scores = np.dot(Q, K.T)

# Step 3: Scale the scores (optinional but common)
dk = Q.shape[1] # dimension of key vectors
scaled_scores = scores / np.sqrt(dk)

# Step 4: Compute softmax to get attention weights
attention_weights = np.exp(scaled_scores) / np.sum(np.exp(scaled_scores), axis=1, keepdims=True)

# Step 5: Multitly attention weights with values matrix to get output
output = np.dot(attention_weights, V)

# Display results
print("Query (Q):")
print(Q)
print("\nKey Vectors (K):")
print(K)
print("\nValue Vectors (V):")
print(V)
print("\nAttention Weights:")
print(attention_weights)
print("\nScaled Scores:")
print(scaled_scores)
print("\nOutput:")
print(output)

Query (Q):
[[1 0 1]]

Key Vectors (K):
[[1 1 0]
 [1 1 0]
 [0 0 1]]

Value Vectors (V):
[[1 2]
 [0 3]
 [1 1]]

Attention Weights:
[[0.33333333 0.33333333 0.33333333]]

Scaled Scores:
[[0.57735027 0.57735027 0.57735027]]

Output:
[[0.66666667 2.        ]]
